### ISSUE TITLE
Stray 's'

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/js-jquery-prevent-default-lab#3]
I keep having strange problems with my environment, but luckily this one was with the lab. 

js/jquery-2.1.1.min.js reads:

`s/*! jQuery v2.1.1 | (c) 2005, 2014 jQuery....`

You'll note there is a stray 's' there that causes all sorts of problems.

**Comment by AnnJohn** [comment]
thanks! this should be fixed now.
